package com.gigaspaces.dih.model.types;

import com.gigaspaces.document.SpaceDocument;
import com.gigaspaces.metadata.SpaceTypeDescriptor;
import com.gigaspaces.metadata.SpaceTypeDescriptorBuilder;
import com.gigaspaces.metadata.index.SpaceIndexType;

/**
 * This class was auto-generated by GigaSpaces
 */
public class companyDb_companySchema_EmployeeDocument extends SpaceDocument {

    private static final long serialVersionUID = 1L;
    private static final String EMPLOYEE = "Employee";
    private static final String EMPLOYEEID = "employeeId";
    private static final String NAME = "naME";
    private static final String MY_AGE = "My_Age";


    public companyDb_companySchema_EmployeeDocument() {
        super(EMPLOYEE);
    }

    public static SpaceTypeDescriptor getTypeDescriptor() {
        return new SpaceTypeDescriptorBuilder(EMPLOYEE)
                .broadcast(false)
                .documentWrapperClass(companyDb_companySchema_EmployeeDocument.class)
                .binaryStorage()
                .addFixedProperty(EMPLOYEEID, Long.class)
                .idProperty(EMPLOYEEID, false, SpaceIndexType.EQUAL)
                .addFixedProperty(NAME, String.class)
                .addPropertyIndex(NAME, SpaceIndexType.EQUAL)
                .addFixedProperty(MY_AGE, Integer.class)
                .routingProperty(MY_AGE, SpaceIndexType.EQUAL_AND_ORDERED)
                .create();
    }

    public Long getEmployeeId() {
        return getProperty(EMPLOYEEID);
    }

    public void setEmployeeId(Long employeeId) {
        setProperty(EMPLOYEEID, employeeId);
    }

    public String getNaME() {
        return getProperty(NAME);
    }

    public void setNaME(String naME) {
        setProperty(NAME, naME);
    }

    public Integer getMy_Age() {
        return getProperty(MY_AGE);
    }

    public void setMy_Age(Integer my_Age) {
        setProperty(MY_AGE, my_Age);
    }


    @Override
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof companyDb_companySchema_EmployeeDocument))
            return false;

        companyDb_companySchema_EmployeeDocument other = (companyDb_companySchema_EmployeeDocument) obj;
        if (!this.getEmployeeId().equals(other.getEmployeeId())) {
            return false;
        }
        if (!this.getNaME().equals(other.getNaME())) {
            return false;
        }
        if (!this.getMy_Age().equals(other.getMy_Age())) {
            return false;
        }
        return true;
    }

}
