package com.gigaspaces.dih.model.types;

import com.gigaspaces.document.SpaceDocument;
import com.gigaspaces.metadata.SpaceTypeDescriptor;
import com.gigaspaces.metadata.SpaceTypeDescriptorBuilder;
import com.gigaspaces.metadata.index.SpaceIndexType;

/**
 * This class was auto-generated by GigaSpaces
 */
public class StudentDocument extends SpaceDocument {

    private static final long serialVersionUID = 1L;
    private static final String STUDENT = "Student";
    private static final String STUDENTID = "studentId";
    private static final String NAME = "name";
    private static final String AGE = "age";


    public StudentDocument() {
        super(STUDENT);
    }

    public static SpaceTypeDescriptor getTypeDescriptor() {
        return new SpaceTypeDescriptorBuilder(STUDENT)
                .broadcast(false)
                .documentWrapperClass(StudentDocument.class)
                .binaryStorage()
                .addFixedProperty(STUDENTID, Long.class)
                .idProperty(STUDENTID, false, SpaceIndexType.EQUAL)
                .addFixedProperty(NAME, String.class)
                .addPropertyIndex(NAME, SpaceIndexType.EQUAL)
                .addFixedProperty(AGE, Integer.class)
                .routingProperty(AGE, SpaceIndexType.EQUAL_AND_ORDERED)
                .create();
    }

    public Long getStudentId() {
        return getProperty(STUDENTID);
    }

    public void setStudentId(Long studentId) {
        setProperty(STUDENTID, studentId);
    }

    public String getName() {
        return getProperty(NAME);
    }

    public void setName(String name) {
        setProperty(NAME, name);
    }

    public Integer getAge() {
        return getProperty(AGE);
    }

    public void setAge(Integer age) {
        setProperty(AGE, age);
    }


    @Override
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof StudentDocument))
            return false;

        StudentDocument other = (StudentDocument) obj;
        if (!this.getStudentId().equals(other.getStudentId())) {
            return false;
        }
        if (!this.getName().equals(other.getName())) {
            return false;
        }
        if (!this.getAge().equals(other.getAge())) {
            return false;
        }
        return true;
    }

}
