package org.gigaspaces.blueprints;

import com.gigaspaces.data_integration.consumer.CDCInfo;
import com.gigaspaces.data_integration.model.types.COMPANYDocument;
import com.gigaspaces.data_integration.model.types.EmployeeDocument;
import com.gigaspaces.data_integration.model.types.EmployeeOverrideDocument;
import org.openspaces.core.GigaSpace;
import org.openspaces.core.GigaSpaceTypeManager;

/**
 * This class was auto-generated by GigaSpaces
 */
public class TypeRegistrar {
    public static void registerTypes(GigaSpace gigaspace) {
        GigaSpaceTypeManager typeManager = gigaspace.getTypeManager();

        typeManager.registerTypeDescriptor(CDCInfo.getTypeDescriptor());
        typeManager.registerTypeDescriptor(COMPANYDocument.getTypeDescriptor());
        typeManager.registerTypeDescriptor(EmployeeDocument.getTypeDescriptor());
        typeManager.registerTypeDescriptor(EmployeeOverrideDocument.getTypeDescriptor());
    }
}
