package com.gigaspaces.dih.model;

import com.gigaspaces.dih.model.types.EmployeeDocument;
import com.gigaspaces.dih.model.types.StudentDocument;
import com.gigaspaces.dih.consumer.CDCInfo;
import org.openspaces.core.GigaSpace;
import org.openspaces.core.GigaSpaceTypeManager;

/**
 * This class was auto-generated by GigaSpaces
 */
public class PipelineTypeRegistrar {
    public static void registerTypes(GigaSpace gigaspace) {
        GigaSpaceTypeManager typeManager = gigaspace.getTypeManager();

        typeManager.registerTypeDescriptor(CDCInfo.getTypeDescriptor());
        typeManager.registerTypeDescriptor(EmployeeDocument.getTypeDescriptor());
        typeManager.registerTypeDescriptor(StudentDocument.getTypeDescriptor());
    }
}
