package com.gigaspaces.dih;

import com.gigaspaces.dih.consumer.web.GSConsumerHandler;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * This class was auto-generated by GigaSpaces
 */
@Configuration
public class ServiceConfig {

    private String diConsumerName;
    private String webPort;

    public ServiceConfig() {
    }

    public ServiceConfig(String diConsumerName,
                         String webPort) {
        this.diConsumerName = diConsumerName;
        this.webPort = webPort;
    }

    @Bean(name = "GSConsumerHandler")
    public GSConsumerHandler myBean() {
        return new GSConsumerHandler(
                diConsumerName,
                Integer.parseInt(webPort));
    }


}
