package {{project.package}};

import com.gigaspaces.dih.consumer.web.PipelineConsumerServlet;
import {{project.package}}.model.PipelineTypeRegistrar;
import com.gigaspaces.internal.client.spaceproxy.ISpaceProxy;
import org.openspaces.core.GigaSpace;
import org.openspaces.core.GigaSpaceConfigurer;
import javax.servlet.ServletContext;

/**
 * This class was auto-generated by GigaSpaces
 */
public class {{project.name}}PipelineConsumerServlet extends PipelineConsumerServlet {

    @Override
    public void registerTypes(ISpaceProxy spaceProxy) {
        PipelineTypeRegistrar.registerTypes(new GigaSpaceConfigurer(spaceProxy).create());
    }

    @Override
    protected ISpaceProxy getSpace(ServletContext servletContext) {
        GigaSpace gigaSpace = (GigaSpace) servletContext.getAttribute("gigaSpace");
        return (ISpaceProxy) gigaSpace.getSpace();
    }
}