project:
  groupId: com.mycompany.app
  artifactId: my-app
  version: 0.1
#java.version: 1.8
#java.version: 11

# Space settings
space:
  name: demo

# Database and hibernate settings
db:
  name: demo-db
  url: jdbc:hsqldb:hsql://localhost/demo-db
  user: sa
  password: ""
  driver:
    class: org.hsqldb.jdbc.JDBCDriver
    groupId: org.hsqldb
    artifactId: hsqldb
    version: 2.5.2
  demo:
    enabled: true

hibernate:
  version: 5.3.10.Final
  dialect: org.hibernate.dialect.HSQLDialect

topology:
  partitions: 1
  ha: true
resources:
  space:
    memory: 512m
  mirror:
    memory: 256m